// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIED9ESFmhhHemd-GEz8VlRCyaZyAFm2M',
    appId: '1:65763368261:web:d90181973d6daa6670322c',
    messagingSenderId: '65763368261',
    projectId: 'attendance-portal-d88dc',
    authDomain: 'attendance-portal-d88dc.firebaseapp.com',
    storageBucket: 'attendance-portal-d88dc.firebasestorage.app',
    measurementId: 'G-181LYT0M7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MKhW26hHiGmT_dq3fyGa6LoWX4Iimpw',
    appId: '1:65763368261:android:6ca7b45a0c878a2070322c',
    messagingSenderId: '65763368261',
    projectId: 'attendance-portal-d88dc',
    storageBucket: 'attendance-portal-d88dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPaLwF5IQJrHNxpk_hKjEs-GVVwVWY4W0',
    appId: '1:65763368261:ios:9250b3ad40a2963870322c',
    messagingSenderId: '65763368261',
    projectId: 'attendance-portal-d88dc',
    storageBucket: 'attendance-portal-d88dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPaLwF5IQJrHNxpk_hKjEs-GVVwVWY4W0',
    appId: '1:65763368261:ios:9250b3ad40a2963870322c',
    messagingSenderId: '65763368261',
    projectId: 'attendance-portal-d88dc',
    storageBucket: 'attendance-portal-d88dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIED9ESFmhhHemd-GEz8VlRCyaZyAFm2M',
    appId: '1:65763368261:web:3f92738e7e4c651a70322c',
    messagingSenderId: '65763368261',
    projectId: 'attendance-portal-d88dc',
    authDomain: 'attendance-portal-d88dc.firebaseapp.com',
    storageBucket: 'attendance-portal-d88dc.firebasestorage.app',
    measurementId: 'G-L8D8ZNDNHY',
  );
}
